version: '3.3'
services:
    shairport-sync:
        restart: always
        network_mode: host
        devices:
          - /dev/snd
        volumes:
          - ./config/shairport-sync.conf:/etc/shairport-sync.conf
        image: mikebrady/shairport-sync

    shairport-scan:
        restart: no
        devices:
          - /dev/snd
        image: mikebrady/sps-alsa-explore
